var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  language: "Français",
  title: "Ardublockly",
  blocks: "Blocs",
  linkTooltip: "Sauve et lie aux blocs.",
  runTooltip: "Execute le programme défini par les blocs dans l'espace de travail.",
  badCode: "Erreur de programme :\n%1",
  timeout: "Nombre maximum d'iterations atteint.",
  discard: "Supprimer tous les blocs %1?",
  trashTooltip: "Abandonner tous les blocs.",
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  catInputOutput: "Entree/Sortie",
  catTime: "Temps",
  catMusic: "Sons",
  catMotors: "Moteurs",
  catComms: "Comms",
  textVariable: "text",
  httpRequestError: "La requête a causé un problème.",
  linkAlert: "Partagez vos blocs avec ce lien:\n\n%1",
  hashError: "Désolé, '%1' ne correspond à aucun programme sauvegardé.",
  xmlError: "Impossible de charger votre programme. Peut-être a-t'il été créé avec une autre version de (Ardu)Blockly?",
  badXml: "Erreur d'analyse XML:\n%1\n\nSélectionnez 'OK' pour abandonner vos changements ou 'Cancel' pour continuer à éditer le fichier XML."
};
