var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "Nederlands",
  title: "Ardublockly",
  blocks: "Blocks",
  /* Menu */
  open: "Open",
  save: "Save",
  deleteAll: "Verwijder Alles",
  settings: "",
  documentation: "Documentatie",
  reportBug: "",
  examples: "Voorbeelden",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  arduinoBoard: "",
  arduinoBoardDefault: "",
  comPort: "",
  comPortDefault: "",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Taal",
  languageDefault: "Language onbekend",
  sketchName:  "",
  /* Arduino console output */
  arduinoOpMainTitle:  "",
  arduinoOpWaiting:  "",
  arduinoOpUploadedTitle:  "",
  arduinoOpVerifiedTitle:  "",
  arduinoOpOpenedTitle:  "",
  arduinoOpOpenedBody:  "",
  arduinoOpErrorUpVerTitle:  "",
  arduinoOpErrorSketchTitle:  "",
  arduinoOpErrorFlagTitle:  "",
  arduinoOpErrorFlagPrefTitle:  "",
  arduinoOpErrorIdeDirTitle:  "",
  arduinoOpErrorIdeDirBody:  "",
  arduinoOpErrorIdeOptionTitle:  "",
  arduinoOpErrorIdeOptionBody:  "",
  arduinoOpErrorIdePortTitle:  "",
  arduinoOpErrorIdePortBody:  "",
  arduinoOpErrorIdeBoardTitle:  "",
  arduinoOpErrorIdeBoardBody:  "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody:  "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "",
  uploadSketch: "",
  verifyingSketch: "",
  verifySketch: "",
  openingSketch: "",
  openSketch: "",
  notImplemented: "",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuleer",
  return: "Terugkeer",
  /* Cards */
  arduinoSourceCode: "",
  blocksXml: "Blocks XML",
  /* Toolbox Categories*/
  catLogic: "Logica",
  catLoops: "Herhalen",
  catMath: "Wiskunde",
  catText: "Tekst",
  catVariables: "Variabelen",
  catFunctions: "Functies",
  catInputOutput: "In/Output",
  catTime: "Tijd",
  catAudio: "Audio",
  catMotors: "Motoren",
  catComms: "Comms",
};
