var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "Français",
  title: "Ardublockly",
  blocks: "Blocs",
  /* Menu */
  open: "Ouvrir",
  save: "Enregistrer",
  deleteAll: "Abandonner Tous",
  settings: "",
  documentation: "Documentation",
  reportBug: "",
  examples: "Examples",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  arduinoBoard: "Carte Arduino",
  arduinoBoardDefault: "Carte Arduino inconnu",
  comPort: "",
  comPortDefault: "",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Langue",
  languageDefault: "Langue inconnu",
  sketchName: "Nom de Sketch",
  /* Arduino console output */
  arduinoOpMainTitle: "",
  arduinoOpWaiting: "",
  arduinoOpUploadedTitle: "",
  arduinoOpVerifiedTitle: "",
  arduinoOpOpenedTitle: "",
  arduinoOpOpenedBody: "",
  arduinoOpErrorUpVerTitle: "",
  arduinoOpErrorSketchTitle: "",
  arduinoOpErrorFlagTitle: "",
  arduinoOpErrorFlagPrefTitle: "",
  arduinoOpErrorIdeDirTitle: "",
  arduinoOpErrorIdeDirBody: "",
  arduinoOpErrorIdeOptionTitle: "",
  arduinoOpErrorIdeOptionBody: "",
  arduinoOpErrorIdePortTitle: "",
  arduinoOpErrorIdePortBody: "",
  arduinoOpErrorIdeBoardTitle: "",
  arduinoOpErrorIdeBoardBody: "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody: "",
  noServerNoLangBody: "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "",
  uploadSketch: "",
  verifyingSketch: "",
  verifySketch: "",
  openingSketch: "",
  openSketch: "",
  notImplemented: "",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuler",
  return: "Retour",
  /* Cards */
  arduinoSourceCode: "",
  blocksXml: "Blocs XML",
  /* Toolbox Categories*/
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  catInputOutput: "Entree/Sortie",
  catTime: "Temps",
  catAudio: "Audio",
  catMotors: "Moteurs",
  catComms: "Comms",
};
