// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof puzzlepage == 'undefined') { var puzzlepage = {}; }


puzzlepage.start = function(opt_data, opt_ignored, opt_ijData) {
  return '<div id="MSG" style="display: none"><span id="country1">Australia</span><span id="country1Flag">flag_au.png</span><span id="country1FlagHeight">50</span><span id="country1FlagWidth">100</span><span id="country1Language">Inglés</span><span id="country1City1">Melbourne</span><span id="country1City2">Sydney</span><span id="country1HelpUrl">http://es.wikipedia.org/wiki/Australia</span><span id="country2">Alemania</span><span id="country2Flag">flag_de.png</span><span id="country2FlagHeight">60</span><span id="country2FlagWidth">100</span><span id="country2Language">Alemán</span><span id="country2City1">Berlín</span><span id="country2City2">Múnich</span><span id="country2HelpUrl">http://es.wikipedia.org/wiki/Alemania</span><span id="country3">China</span><span id="country3Flag">flag_cn.png</span><span id="country3FlagHeight">66</span><span id="country3FlagWidth">100</span><span id="country3Language">Chino</span><span id="country3City1">Pekín</span><span id="country3City2">Shanghái</span><span id="country3HelpUrl">http://es.wikipedia.org/wiki/China</span><span id="country4">Brasil</span><span id="country4Flag">flag_br.png</span><span id="country4FlagHeight">70</span><span id="country4FlagWidth">100</span><span id="country4Language">Portugués</span><span id="country4City1">Río de Janeiro</span><span id="country4City2">São Paulo</span><span id="country4HelpUrl">http://es.wikipedia.org/wiki/Brasil</span><span id="flag">bandera</span><span id="language">idioma:</span><span id="languageChoose">elegir...</span><span id="cities">ciudades:</span><span id="error0">¡Perfecto!\nLos %1 bloques están bien colocados.</span><span id="error1">¡Casi! Un bloque está mal colocado.</span><span id="error2">%1 bloques están mal colocados.</span><span id="tryAgain">El bloque destacado está mal colocado.\nSigue intentándolo.</span></div><table id="header" width="100%"><tr><td valign="bottom"><h1><span id="title"><a href="../index.html">Blockly</a> : Puzle</span></h1></td><td><select id="languageMenu" onchange="BlocklyApps.changeLanguage();"></select>&nbsp; &nbsp;<button id="helpButton" onclick="Puzzle.showHelp();">Ayuda</button>&nbsp; &nbsp;<button id="checkButton" class="launch" onclick="Puzzle.checkAnswers();">Comprobar las respuestas</button></td></tr></table><script type="text/javascript" src="../../blockly_compressed.js"><\/script><script type="text/javascript" src="../../' + soy.$$escapeHtml(opt_ijData.langSrc) + '"><\/script><script type="text/javascript" src="blocks.js"><\/script><div id="blockly"></div><div id="shadow"></div><div id="help"><div style="padding-bottom: 0.7ex">Para cada país (verde), asocia su bandera, elige su idioma y agrupa sus ciudades.</div><div><img src="help/help_es.png"></div><div class="farSide" style="padding: 1ex 3ex 0"><button id="okButton" onclick="Puzzle.hideHelp()">Aceptar</button></div></div>';
};
