// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof puzzlepage == 'undefined') { var puzzlepage = {}; }


puzzlepage.start = function(opt_data, opt_ignored, opt_ijData) {
  return '<div id="MSG" style="display: none"><span id="country1">Australie</span><span id="country1Flag">flag_au.png</span><span id="country1FlagHeight">50</span><span id="country1FlagWidth">100</span><span id="country1Language">Anglais</span><span id="country1City1">Melbourne</span><span id="country1City2">Sydney</span><span id="country1HelpUrl">http://fr.wikipedia.org/wiki/Australie</span><span id="country2">Allemagne</span><span id="country2Flag">flag_de.png</span><span id="country2FlagHeight">60</span><span id="country2FlagWidth">100</span><span id="country2Language">Allemand</span><span id="country2City1">Berlin</span><span id="country2City2">Munich</span><span id="country2HelpUrl">http://fr.wikipedia.org/wiki/Allemagne</span><span id="country3">Chine</span><span id="country3Flag">flag_cn.png</span><span id="country3FlagHeight">66</span><span id="country3FlagWidth">100</span><span id="country3Language">Chinois</span><span id="country3City1">Pékin</span><span id="country3City2">Shanghai</span><span id="country3HelpUrl">http://fr.wikipedia.org/wiki/Chine</span><span id="country4">Brésil</span><span id="country4Flag">flag_br.png</span><span id="country4FlagHeight">70</span><span id="country4FlagWidth">100</span><span id="country4Language">Portugais</span><span id="country4City1">Rio de Janeiro</span><span id="country4City2">São Paulo</span><span id="country4HelpUrl">http://fr.wikipedia.org/wiki/Br%C3%A9sil</span><span id="flag">flag:</span><span id="language">langue:</span><span id="languageChoose">choisis...</span><span id="cities">villes:</span><span id="error0">Parfait!  Tous les %1 blocs sont corrects.</span><span id="error1">Presque!  Un block est incorrect.</span><span id="error2">%1 blocks sont incorrects.</span><span id="tryAgain">Le bloc en surbrillance est incorrect.  Ressaie.</span></div><table id="header" width="100%"><tr><td valign="bottom"><h1><span id="title"><a href="../index.html"><span id="blocklyName">Blockly</span></a> : Puzzle</span></h1></td><td class="farSide"><select id="languageMenu" onchange="Puzzle.changeLanguage();"></select>&nbsp; &nbsp;<button id="helpButton" onclick="Puzzle.showHelp();">Aider</button>&nbsp; &nbsp;<button id="checkButton" class="launch" onclick="Puzzle.checkAnswers();">Vérifiez les réponses</button></td></tr></table><script type="text/javascript" src="../../blockly_compressed.js"><\/script><script type="text/javascript" src="../../' + soy.$$escapeHtml(opt_ijData.langSrc) + '"><\/script><script type="text/javascript" src="blocks.js"><\/script><div id="blockly"></div><div id="shadow"></div><div id="help"><div style="padding-bottom: 0.7ex">Pour chaque pays (en vert), attache son drapeau, choisis sa langue, et fais un empilage de ses villes.</div><div><img src="help/help_fr.png"></div><div class="farSide" style="padding: 1ex 3ex 0"><button id="okButton" onclick="Puzzle.hideHelp()">OK</button></div></div>';
};
