// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof puzzlepage == 'undefined') { var puzzlepage = {}; }


puzzlepage.start = function(opt_data, opt_ignored) {
  return '<div id="MSG" style="display:none"><span id="country1">Ausztrália</span><span id="country1Flag">flag_au.png</span><span id="country1FlagHeight">50</span><span id="country1FlagWidth">100</span><span id="country1Language">Angol</span><span id="country1City1">Melbourne</span><span id="country1City2">Sydney</span><span id="country1HelpUrl">http://hu.wikipedia.org/wiki/Ausztrália</span><span id="country2">Németország</span><span id="country2Flag">flag_de.png</span><span id="country2FlagHeight">60</span><span id="country2FlagWidth">100</span><span id="country2Language">Német</span><span id="country2City1">Berlin</span><span id="country2City2">München</span><span id="country2HelpUrl">http://hu.wikipedia.org/wiki/Németország</span><span id="country3">Kína</span><span id="country3Flag">flag_cn.png</span><span id="country3FlagHeight">66</span><span id="country3FlagWidth">100</span><span id="country3Language">Kínai</span><span id="country3City1">Peking</span><span id="country3City2">Sanghaj</span><span id="country3HelpUrl">http://hu.wikipedia.org/wiki/Kína</span><span id="country4">Brazília</span><span id="country4Flag">flag_br.png</span><span id="country4FlagHeight">70</span><span id="country4FlagWidth">100</span><span id="country4Language">Portugál</span><span id="country4City1">Rio de Janeiro</span><span id="country4City2">São Paulo</span><span id="country4HelpUrl">http://hu.wikipedia.org/wiki/Brazília</span><span id="flag">zászló</span><span id="language">nyelv:</span><span id="languageChoose">válassz…</span><span id="cities">városok:</span><span id="error0">Tökéletes!\nMinden %1 blokk helyes.</span><span id="error1">Majdnem sikerült! Egy blokk helytelen.</span><span id="error2">%1 blokk helytelen.</span><span id="tryAgain">A kiemelt blokk helytelen.\nPróbálkozz tovább!</span><span id="fullTitle">Blokkrejtvény</span></div><table id="header" width="100%"><tr><td valign="bottom"><h1><a href="http://blockly.googlecode.com/">Blockly</a><span class="ltrShow"> &gt; </span><span class="rtlShow"> &lt; </span><a href="../index.html">Apps</a><span class="ltrShow"> &gt; </span><span class="rtlShow"> &lt; </span>Rejtvény</h1></td><td class="farSide"><button id="helpButton" onclick="Puzzle.showHelp();">Segítség</button><button id="checkButton" class="launch" onclick="Puzzle.checkAnswers();">Válaszok ellenőrzése</button></td></tr></table><script type="text/javascript" src="blocks.js"><\/script><div id="blockly"></div><div id="shadow"></div><div id="help"><div style="padding-bottom: 0.7ex">Minden országhoz (zöld színűek) add hozzá a zászlóját, válaszd ki a nyelvet amit beszélnek és készíts egy tornyot a városaiból.</div><div><img src="help/help_en.png"></div><div class="farSide" style="padding: 1ex 3ex 0"><button id="okButton" onclick="Puzzle.hideHelp()">Elolvastam</button></div></div>';
};
