// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof puzzlepage == 'undefined') { var puzzlepage = {}; }


puzzlepage.start = function(opt_data, opt_ignored) {
  return '<div id="MSG" style="display:none"><span id="country1">Ausztrália</span><span id="country1Flag">flag_au.png</span><span id="country1FlagHeight">50</span><span id="country1FlagWidth">100</span><span id="country1Language">Angol</span><span id="country1City1">Melbourne</span><span id="country1City2">Sydney</span><span id="country1HelpUrl">http://hu.wikipedia.org/wiki/Ausztr%C3%A1lia_(orsz%C3%A1g)</span><span id="country2">Németország</span><span id="country2Flag">flag_de.png</span><span id="country2FlagHeight">60</span><span id="country2FlagWidth">100</span><span id="country2Language">Német</span><span id="country2City1">Berlin</span><span id="country2City2">München</span><span id="country2HelpUrl">http://hu.wikipedia.org/wiki/N%C3%A9metorsz%C3%A1g</span><span id="country3">Kína</span><span id="country3Flag">flag_cn.png</span><span id="country3FlagHeight">66</span><span id="country3FlagWidth">100</span><span id="country3Language">Kínai</span><span id="country3City1">Peking</span><span id="country3City2">Sanghaj</span><span id="country3HelpUrl">http://hu.wikipedia.org/wiki/K%C3%ADna</span><span id="country4">Brazília</span><span id="country4Flag">flag_br.png</span><span id="country4FlagHeight">70</span><span id="country4FlagWidth">100</span><span id="country4Language">Portugál</span><span id="country4City1">Rio de Janeiro</span><span id="country4City2">São Paulo</span><span id="country4HelpUrl">http://hu.wikipedia.org/wiki/Braz%C3%ADlia</span><span id="flag">zászló:</span><span id="language">nyelv:</span><span id="languageChoose">válassz...</span><span id="cities">városok:</span><span id="error0">Tökéletes!\nMind a %1 blokk a helyén van.</span><span id="error1">Majdnem! 1 blokk rosz helyre került.</span><span id="error2">%1 blokk rosz helyre került.</span><span id="tryAgain">A kiemelt blokk nincs a helyén.\nPróbáld újra.</span><span id="fullTitle">Blockly Puzzle</span></div><table id="header" width="100%"><tr><td valign="bottom"><h1><a href="http://blockly.googlecode.com/">Blockly</a> &gt; <a href="../index.html">Apps</a> &gt;Puzzle</h1></td><td align="right"><button id="helpButton" onclick="Puzzle.showHelp();">Sugó</button><button id="checkButton" class="launch" onclick="Puzzle.checkAnswers();">Válaszok ellenőrzése</button></td></tr></table><script type="text/javascript" src="blocks.js"><\/script><div id="blockly"></div><div id="shadow"></div><div id="help"><div style="padding-bottom: 0.7ex">Minden országot jelképező blokkhoz (zöld), kapcsold hozzá a zászlóját, válaszd ki a hivatalos nyelvét, illetve a városait.</div><div><img src="help_hu.png"></div><div style="text-align: right; padding-top: 1ex; padding-right: 3ex"><button id="okButton" onclick="Puzzle.hideHelp()">OK</button></div></div>';
};
