// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof puzzlepage == 'undefined') { var puzzlepage = {}; }


puzzlepage.start = function(opt_data, opt_ignored) {
  return '<div id="MSG" style="display:none"><span id="country1">オーストラリア</span><span id="country1Flag">flag_au.png</span><span id="country1FlagHeight">50</span><span id="country1FlagWidth">100</span><span id="country1Language">英語</span><span id="country1City1">メルボルン</span><span id="country1City2">シドニー</span><span id="country1HelpUrl">http://ja.wikipedia.org/wiki/オーストラリア</span><span id="country2">ドイツ</span><span id="country2Flag">flag_de.png</span><span id="country2FlagHeight">60</span><span id="country2FlagWidth">100</span><span id="country2Language">ドイツ語</span><span id="country2City1">ベルリン</span><span id="country2City2">ミュンヘン</span><span id="country2HelpUrl">http://ja.wikipedia.org/wiki/ドイツ</span><span id="country3">中国</span><span id="country3Flag">flag_cn.png</span><span id="country3FlagHeight">66</span><span id="country3FlagWidth">100</span><span id="country3Language">中国語</span><span id="country3City1">北京</span><span id="country3City2">上海</span><span id="country3HelpUrl">http://ja.wikipedia.org/wiki/中華人民共和国</span><span id="country4">ブラジル</span><span id="country4Flag">flag_br.png</span><span id="country4FlagHeight">70</span><span id="country4FlagWidth">100</span><span id="country4Language">ポルトガル語</span><span id="country4City1">リオデジャネイロ</span><span id="country4City2">サンパウロ</span><span id="country4HelpUrl">http://ja.wikipedia.org/wiki/ブラジル</span><span id="flag">国旗</span><span id="language">言語:</span><span id="languageChoose">選んでください...</span><span id="cities">都市:</span><span id="error0">Perfect!\\nAll %1 blocks are correct.</span><span id="error1">惜しい! 1 個のブロックが間違っています。</span><span id="error2">%1 個のブロックが間違っています。</span><span id="tryAgain">The highlighted block is not correct.\\nKeep trying.</span><span id="fullTitle">ブロックリー パズル</span></div><table id="header" width="100%"><tr><td valign="bottom"><h1><a href="http://blockly.googlecode.com/">Blockly</a><span class="ltrShow"> &gt; </span><span class="rtlShow"> &lt; </span><a href="../index.html">Apps</a><span class="ltrShow"> &gt; </span><span class="rtlShow"> &lt; </span>パズル</h1></td><td class="farSide"><button id="helpButton" onclick="Puzzle.showHelp();">ヘルプ</button><button id="checkButton" class="launch" onclick="Puzzle.checkAnswers();">答え合わせ</button></td></tr></table><script type="text/javascript" src="blocks.js"><\/script><div id="blockly"></div><div id="shadow"></div><div id="help"><div style="padding-bottom: 0.7ex">それぞれの国 (緑) について、国旗をつなげて、言語を選んで、都市を並べてください。</div><div><img src="help_ja.png"></div><div class="farSide" style="padding: 1ex 3ex 0"><button id="okButton" onclick="Puzzle.hideHelp()">OK</button></div></div>';
};
