// This file was automatically generated from template.soy.
// Please don't edit this file by hand.

if (typeof puzzlepage == 'undefined') { var puzzlepage = {}; }


puzzlepage.start = function(opt_data, opt_ignored) {
  return '<div id="MSG" style="display:none"><span id="country1">Австралија</span><span id="country1Flag">flag_au.png</span><span id="country1FlagHeight">50</span><span id="country1FlagWidth">100</span><span id="country1Language">англиски</span><span id="country1City1">Мелбурн</span><span id="country1City2">Сиднеј</span><span id="country1HelpUrl">http://mk.wikipedia.org/wiki/Австралија</span><span id="country2">Германија</span><span id="country2Flag">flag_de.png</span><span id="country2FlagHeight">60</span><span id="country2FlagWidth">100</span><span id="country2Language">германски</span><span id="country2City1">Берлин</span><span id="country2City2">Минхен</span><span id="country2HelpUrl">http://mk.wikipedia.org/wiki/Германија</span><span id="country3">Кина</span><span id="country3Flag">flag_cn.png</span><span id="country3FlagHeight">66</span><span id="country3FlagWidth">100</span><span id="country3Language">кинески</span><span id="country3City1">Пекинг</span><span id="country3City2">Шангај</span><span id="country3HelpUrl">http://mk.wikipedia.org/wiki/Кина</span><span id="country4">Бразил</span><span id="country4Flag">flag_br.png</span><span id="country4FlagHeight">70</span><span id="country4FlagWidth">100</span><span id="country4Language">португалски</span><span id="country4City1">Рио де Жанеиро</span><span id="country4City2">Сао Паоло</span><span id="country4HelpUrl">http://mk.wikipedia.org/wiki/Бразил</span><span id="flag">знаме</span><span id="language">јазик:</span><span id="languageChoose">одберете...</span><span id="cities">градови:</span><span id="error0">Совршено!\nСите %1 блокови се точни.</span><span id="error1">За малку! Само еден блок е грешен.</span><span id="error2">Има %1 грешни блокови.</span><span id="tryAgain">Потцртаниот блок не е исправен.\nОбидувајте се и понатаму.</span><span id="fullTitle">Блокли - Сложувалка</span></div><table id="header" width="100%"><tr><td valign="bottom"><h1><a href="http://blockly.googlecode.com/">Blockly</a><span class="ltrShow"> &gt; </span><span class="rtlShow"> &lt; </span><a href="../index.html">Apps</a><span class="ltrShow"> &gt; </span><span class="rtlShow"> &lt; </span>Сложувалка</h1></td><td class="farSide"><button id="helpButton" onclick="Puzzle.showHelp();">Помош</button><button id="checkButton" class="launch" onclick="Puzzle.checkAnswers();">Провери одговори</button></td></tr></table><script type="text/javascript" src="blocks.js"><\/script><div id="blockly"></div><div id="shadow"></div><div id="help"><div style="padding-bottom: 0.7ex">За секоја земја (зелено), прикачете го знамето, изберете кој јазик го зборува и наредете ги градовите.</div><div><img src="help_mk.png"></div><div class="farSide" style="padding: 1ex 3ex 0"><button id="okButton" onclick="Puzzle.hideHelp()">ОК</button></div></div>';
};
